{% set name = "arrest" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arrest-{{ version }}.tar.gz
  sha256: 5d4cdd2fb3cbf0214ed2bdc99c2debe91a8175ddbb99646eb1281494b12956c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - pydantic >=1.10.13
    - httpx >=0.24.1,<0.25.0
    - orjson >=3.9.10,<4.0.0
    - pyyaml >=6.0.1,<7.0.0
    - openapi-pydantic >=0.4.0,<0.5.0
    - backoff >=2.2.1,<3.0.0

test:
  imports:
    - arrest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/s-bose/arrest
  doc_url: https://s-bose.github.io/arrest
  summary: Arrest is a wrapper of pydantic and httpx to make your REST api calls type-safe and structured
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
